### ISSUE TITLE
LED Interface

### ISSUE THREAD

**Issue by mikeshams** [vyhoangquocnguyen/CapstoneProject_G1#10]
Can you use the PWM output pins to control the brightness in terms of coding?

**Comment by ManuSimriti** [comment]
It is not possible to control LED strip's brightness because we are controlling the LED strips using a relay and controlling the relay using gpio via logic level converter even if we use PWM pins the relay is only switched at a particular level of current and the current going to LED strip is coming directly from 12V supply. So, we were not able to control brightness through PWM pins of raspberry Pi.
