### ISSUE TITLE
Temperature Sensor Interfacing

### ISSUE THREAD

**Issue by mikeshams** [vyhoangquocnguyen/CapstoneProject_G1#5]
1. Your ppt file was short. Add more related references.
2. Explain about fnctl header file

**Comment by Annajoy-Techi** [comment]
Dear Sir, 
Since my ppt was short I have added more slides and theory. I have uploaded my ppt file to the main branch.

**fcntl header file** is used to define file control options.
It defines values for the fcntl and open subroutines.
The /usr/include/fcntl.h file defines the values that can be specified for the Command and Argument parameters of the fcntl subroutine and for the Oflag parameter of the open subroutine.
